# list of labels and minimatch globs to match to apply the label.

CI:
- any: ['.cirrus.yml']
- any: ['.github/dependabot.yml']
- any: ['.github/labeler.yml']
- any: ['.github/workflows/*']
- any: ['.appveyor.yml']
- any: ['.codecov.yml']

documentation:
- all: ['*/doc/*']

translation:
- any: ['src/po/*.po']

if_lua:
- any: ['src/if_lua.c']
- any: ['src/proto/if_lua.pro']
- any: ['runtime/doc/if_lua.txt']

if_mzscheme:
- any: ['src/if_mzsch.c']
- any: ['src/if_mzsch.h']
- any: ['src/proto/if_mzsch.pro']
- any: ['runtime/doc/if_mzsch.txt']

if_perl:
- any: ['src/if_perl.xs']
- any: ['src/if_perlsfio.c']
- any: ['src/proto/if_perl.pro']
- any: ['src/proto/if_perlsfio.pro']
- any: ['runtime/doc/if_perl.txt']

if_python:
- any: ['src/if_py_both.h']
- any: ['runtime/doc/if_pyth.txt']
- any: ['src/if_python.c']
- any: ['src/if_python3.c']
- any: ['src/proto/if_python.pro']
- any: ['src/proto/if_python3.pro']

if_ruby:
- any: ['src/if_ruby.c']
- any: ['src/proto/if_ruby.pro']
- any: ['runtime/doc/if_ruby.txt']

if_tcl:
- any: ['src/if_tcl.c']
- any: ['src/proto/if_tcl.pro']
- any: ['runtime/doc/if_tcl.txt']

installer:
- any: ['nsis/**']
- any: ['src/dosinst.*']
- any: ['src/uninstall.c']

platform-mac:
- any: ['src/INSTALLmac.txt']
- any: ['src/os_mac*']
- any: ['src/proto/os_mac*']

platform-windows:
- any: ['nsis/**']
- any: ['src/*.bat']
- any: ['src/*.bmp']
- any: ['src/*.ico']
- any: ['src/GvimExt/*']
- any: ['src/INSTALLpc.txt']
- any: ['src/Make_cyg*.mak']
- any: ['src/Make_ming.mak']
- any: ['src/Make_mvc.mak']
- any: ['src/dosinst.*']
- any: ['src/gui_dwrite.*']
- any: ['src/gui_w32*']
- any: ['src/if_ole.*']
- any: ['src/iid_ole.c']
- any: ['src/os_mswin*']
- any: ['src/os_w32*']
- any: ['src/os_win32.*']
- any: ['src/proto/gui_w32.pro']
- any: ['src/proto/os_mswin.pro']
- any: ['src/proto/os_win32.pro']
- any: ['src/proto/winclip.pro']
- any: ['src/uninstall.c']
- any: ['src/vim.manifest']
- any: ['src/vim.rc']
- any: ['src/vimrun.c']
- any: ['src/winclip.c']
- any: ['src/xpm/**']
- any: ['src/xpm_w32.*']

runtime:
- any: ['runtime/ftplugin']
- any: ['runtime/syntax']
- any: ['runtime/indent']
- any: ['runtime/pack/dist/opt/termdebug/plugin/termdebug.vim']

termdebug: runtime/pack/dist/opt/termdebug/plugin/termdebug.vim

plugin-netrw:
- any: ['runtime/plugin/netrwPlugin.vim']
- any: ['runtime/autoload/netrw*']

xxd:
- any: ['src/xxd/*']
