coverage:
  range: "80...100"
  status:
    project:
      default:
        threshold: 0.05%

comment: false

# Files not run by tests
ignore:
  - "src/dosinst.c"
  - "src/dosinst.h"
  - "src/uninstall.c"
